// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khltqymgtddxkurfbcil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobHRxeW1ndGRkeGt1cmZiY2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTIxODYsImV4cCI6MjA3MDEyODE4Nn0.-hMCTMMT44GJgZ5jlHX6hgYlkUlxgl8qPFdABidmvoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});